spring:
  profiles:
    active: dev
  application:
    name: app

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB 
      max-request-size: 10MB

server:
  port: 9000

logging:
  level: 
    com.example.demo: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 часа в миллисекундах

app:
  upload:
    dir: uploads # Для загрузки файлов

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:}
    chat-id: ${TELEGRAM_CHAT_ID:}

---
spring:
  config:
    activate:
      on-profile: prod
      
server:
  port: 8083